name: Backend Weekly Project
run-name: ${{github.event.head_commit.messages}}
on:
  push:
    tags:
      - v*
jobs:
  backend-express:
    name: "Build image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Login to docker
        run: echo -n ${{secrets.GITHUB_TOKEN}}| docker login ghcr.io --username ${{github.actor}} --password-stdin
      - name: Build images
        run: docker build . -t ghcr.io/${{github.repository}}:latest
      - name: Push to ghcr.io
        run: docker push ghcr.io/${{github.repository}}:latest
      - name: Deployment in server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd server
            docker compose pull backend
            docker compose down migrate
            docker compose up migrate -d
            docker compose up backend -d
